### ISSUE TITLE
Added tool Skyline2Isocor not being integrated onto W4M galaxy UI

### ISSUE THREAD

**Issue by llegregam** [workflow4metabolomics/tools-metabolomics#266]
I finished adding a tool recently to W4M (skyline2isocor), and it seems that it is not being integrated into the UI. Any idea why?

**Comment by lecorguille** [comment]
Indeed!

This is because in this [MR](https://gitlab.com/ifb-elixirfr/usegalaxy-fr/tools/-/merge_requests/622) the owner of skyline2isocor should be [`workflow4metabolomics`](https://toolshed.g2.bx.psu.edu/view/workflow4metabolomics/skyline2isocor/cdb4564fcb68) not `llegregam` since you submitted it through this repo.

Can you propose an MR to fix that?

**Comment by llegregam** [comment]
Thank you!
